# action.yml
---
name: 'EA Tester'
description: 'Runs MQL program'
author: 'kenorb'
inputs:
  MtVersion:
    description: 'Version of the platform to install'
    default: '4.0.0.1260'
  OptTrace:
    description: 'Enables trace mode (debug)'
  OptVerbose:
    description: 'Enables verbose mode'
  Script:
    description: 'The name of the script to run'
  TestPeriod:
    description: 'Timeframe to use for the test'
    default: M30
  TestExpert:
    description: 'The name of the EA to test'
    # required: true
# outputs:
#  foo: # id of output
#    description: 'Foo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BT_PERIOD: ${{ inputs.TestPeriod }}
    OPT_TRACE: ${{ inputs.OptTrace }}
    OPT_VERBOSE: ${{ inputs.OptVerbose }}
    SCRIPT: ${{ inputs.Script }}
    TEST_EXPERT: ${{ inputs.TestExpert }}
branding:
  icon: 'bar-chart'
  color: 'green'
