# action.yml
---
name: 'EA Tester'
description: 'Runs MQL program'
author: 'kenorb'
inputs:
  BtDays:
    description: 'Specifies range of days in each month to test'
    default: '1-31'
  BtMonths:
    description: 'Specifies range of months in each year to test'
    default: '1'
  BtYears:
    description: 'Specifies year or range of years to test'
    default: '2018'
  MtVersion:
    description: 'Version of the platform to install'
    default: '4.0.0.1260'
  OptTrace:
    description: 'Enables trace mode (debug)'
  OptVerbose:
    description: 'Enables verbose mode'
  Script:
    description: 'The name of the script to run'
  TestPeriod:
    description: 'Timeframe to use for the test'
    default: M30
  TestExpert:
    description: 'The name of the EA to test'
    # required: true
  RunOnStart:
    description: "Runs command on startup (before the test)"
  RunOnSet:
    description: "Runs command on SET configuration (before the test)"
  RunOnSuccess:
    description: "Runs command after successful test"
  RunOnError:
    description: "Runs command on error"
  RunOnExit:
    description: "Runs command on exit (after the test)"
  RunOnFail:
    description: "Runs command after test failure"
# outputs:
#  foo: # id of output
#    description: 'Foo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BT_DAYS: ${{ inputs.BtDays }}
    BT_MONTHS: ${{ inputs.BtMonths }}
    BT_PERIOD: ${{ inputs.TestPeriod }}
    BT_YEARS: ${{ inputs.BtYears }}
    OPT_TRACE: ${{ inputs.OptTrace }}
    OPT_VERBOSE: ${{ inputs.OptVerbose }}
    RUN_ON_ERROR: ${{ inputs.RunOnError }}
    RUN_ON_EXIT: ${{ inputs.RunOnExit }}
    RUN_ON_FAIL: ${{ inputs.RunOnFail }}
    RUN_ON_SET: ${{ inputs.RunOnSet }}
    RUN_ON_START: ${{ inputs.RunOnStart }}
    RUN_ON_SUCCESS: ${{ inputs.RunOnSuccess }}
    SCRIPT: ${{ inputs.Script }}
    TEST_EXPERT: ${{ inputs.TestExpert }}
    WORKDIR: "/github/workspace"
branding:
  icon: 'bar-chart'
  color: 'green'
