---
name: Action@dev

on:
  pull_request:
    branches:
      - 'dev*'
    paths-ignore:
      - '*.md'
  push:
    branches:
      - 'dev*'
    paths-ignore:
      - '*.md'

jobs:
  Scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Run PrintPaths
        uses: ea31337/mql-tester-action@dev
        with:
          OptTrace: true
          OptVerbose: true
          Script: "PrintPaths"
  Experts:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Run TestBands
        uses: ea31337/mql-tester-action@dev
        with:
          OptVerbose: true
          TestExpert: "TestBands.mq4"
      - name: Run TestEnvelopes
        uses: ea31337/mql-tester-action@dev
        with:
          OptVerbose: true
          TestExpert: "TestEnvelopes.mq4"
          TestPeriod: M1
      - name: Run TestTimeframes
        uses: ea31337/mql-tester-action@dev
        with:
          OptVerbose: true
          TestExpert: "TestTimeframes.mq4"
