---
name: Action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PrintPaths
        uses: ./
        with:
          Script: PrintPaths
  Experts:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - uses: actions/checkout@v4
      - name: Run TestBands
        uses: ./
        with:
          TestExpert: TestBands.mq4
      - name: Run TestEnvelopes
        uses: ./
        with:
          TestExpert: TestEnvelopes.mq4
          TestPeriod: M1
      - name: Run TestTimeframes
        uses: ./
        with:
          TestExpert: TestTimeframes.mq4
