---
name: Action@dev

on:
  - pull_request
  - push

jobs:
  Scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Run PrintPaths
        uses: ea31337/mql-tester-action@dev
        with:
          OptTrace: true
          OptVerbose: true
          Script: "PrintPaths"
  Experts:
    runs-on: ubuntu-latest
    steps:
      - name: Run TestBands
        uses: ea31337/mql-tester-action@dev
        with:
          OptVerbose: true
          TestExpert: "TestBands.mq4"
