---
name: Action@master

on:
  - pull_request
  - push

jobs:
  Script:
    runs-on: ubuntu-latest
    steps:
      - uses: ea31337/mql-tester-action@master
        with:
          OptTrace: true
          OptVerbose: true
          Script: "PrintPaths"
