---
name: Action

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    paths-ignore:
      - '*.md'

jobs:
  Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run PrintPaths
        uses: ./
        with:
          OptTrace: true
          OptVerbose: true
          Script: "PrintPaths"
  Experts:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - uses: actions/checkout@v2
      - name: Run TestBands
        uses: ./
        with:
          OptVerbose: true
          TestExpert: "TestBands.mq4"
      - name: Run TestEnvelopes
        uses: ./
        with:
          OptVerbose: true
          TestExpert: "TestEnvelopes.mq4"
          TestPeriod: M1
          RunOnFail: "exit 0"
      - name: Run TestTimeframes
        uses: ./
        with:
          OptVerbose: true
          TestExpert: "TestTimeframes.mq4"
