# yamllint disable rule:line-length
---
name: Lint
on:
  - pull_request
  - push
jobs:
  Dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@master
        with:
          dockerfile: Dockerfile
  ShellCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Shell Check
        uses: luizm/action-sh-checker@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sh_checker_comment: true
          sh_checker_shfmt_disable: true
  YAML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: YAML check (yamllint)
        uses: ibiqlik/action-yamllint@master
        with:
          strict: true
